artifact_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/572880046153047884
creation_time: 1754479914865
experiment_id: '572880046153047884'
last_update_time: 1754479914865
lifecycle_stage: active
name: Iris_Random_Forest
