artifact_uri: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/466769356011913422/0ac5bf2d46c3452eab46b99cb253f8df/artifacts
end_time: 1754324421362
entry_point_name: ''
experiment_id: '466769356011913422'
lifecycle_stage: active
run_id: 0ac5bf2d46c3452eab46b99cb253f8df
run_name: merciful-pug-771
source_name: ''
source_type: 4
source_version: ''
start_time: 1754324421315
status: 3
tags: []
user_id: sanjaykumarc
