aliases: []
creation_timestamp: 1754479914831
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1754479914831
metrics: null
model_id: m-1b91f2acaea6409584c490bda14cdaae
name: Iris_Logistic_Regression_Model
params: null
run_id: 78c2ed660c40457eb1ae608ca97faa23
run_link: null
source: models:/m-1b91f2acaea6409584c490bda14cdaae
status: READY
status_message: null
storage_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/399823520799581365/models/m-1b91f2acaea6409584c490bda14cdaae/artifacts
user_id: null
version: 1
