artifact_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/0
creation_time: 1754417922511
experiment_id: '0'
last_update_time: 1754417922511
lifecycle_stage: active
name: Default
