artifact_uri: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/466769356011913422/4bfff16acb30453d9e55780eb73142e4/artifacts
end_time: 1754324180085
entry_point_name: ''
experiment_id: '466769356011913422'
lifecycle_stage: active
run_id: 4bfff16acb30453d9e55780eb73142e4
run_name: inquisitive-owl-545
source_name: ''
source_type: 4
source_version: ''
start_time: 1754324180000
status: 3
tags: []
user_id: sanjaykumarc
