artifact_uri: file:///Users/sanjaykumarc/mlops-assignment/mlflow_logs/162202028662124383/24683a6685184c5595fbe61debcd8cdd/artifacts
end_time: 1754305748985
entry_point_name: ''
experiment_id: '162202028662124383'
lifecycle_stage: active
run_id: 24683a6685184c5595fbe61debcd8cdd
run_name: glamorous-auk-859
source_name: ''
source_type: 4
source_version: ''
start_time: 1754305748964
status: 4
tags: []
user_id: sanjaykumarc
