aliases: []
creation_timestamp: 1754479917886
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1754479917886
metrics: null
model_id: m-dd2a74582cde47cd834706970818367e
name: Iris_Random_Forest_Model
params: null
run_id: a6dd358254184fc9a1b9026e89ecd5da
run_link: null
source: models:/m-dd2a74582cde47cd834706970818367e
status: READY
status_message: null
storage_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/572880046153047884/models/m-dd2a74582cde47cd834706970818367e/artifacts
user_id: null
version: 1
