aliases: []
creation_timestamp: 1754418773302
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1754418773302
metrics: null
model_id: m-58d3cd2cdfc541c08fd2a87951a3048e
name: Iris_Logistic_Regression_Model
params: null
run_id: 3a72423bb4b04a4abf29afa85a7609a9
run_link: null
source: models:/m-58d3cd2cdfc541c08fd2a87951a3048e
status: READY
status_message: null
storage_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/939559991168507879/models/m-58d3cd2cdfc541c08fd2a87951a3048e/artifacts
user_id: null
version: 2
