artifact_uri: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/399823520799581365/78c2ed660c40457eb1ae608ca97faa23/artifacts
end_time: 1754479914860
entry_point_name: ''
experiment_id: '399823520799581365'
lifecycle_stage: active
run_id: 78c2ed660c40457eb1ae608ca97faa23
run_name: omniscient-snail-510
source_name: ''
source_type: 4
source_version: ''
start_time: 1754479910533
status: 3
tags: []
user_id: sanjaykumarc
