artifact_uri: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/466769356011913422/ac980b14bcdd49af8dccf15a47dadd0e/artifacts
end_time: 1754324209646
entry_point_name: ''
experiment_id: '466769356011913422'
lifecycle_stage: active
run_id: ac980b14bcdd49af8dccf15a47dadd0e
run_name: nebulous-mare-769
source_name: ''
source_type: 4
source_version: ''
start_time: 1754324209578
status: 3
tags: []
user_id: sanjaykumarc
