artifact_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/466769356011913422
creation_time: 1754324179381
experiment_id: '466769356011913422'
last_update_time: 1754324179381
lifecycle_stage: active
name: Iris_Logistic_Regression
