artifact_location: file:///Users/sanjaykumarc/mlops-assignment/mlops-assignment/mlflow_logs/939559991168507879
creation_time: 1754417922529
experiment_id: '939559991168507879'
last_update_time: 1754417922529
lifecycle_stage: active
name: Iris_Logistic_Regression
